name: Deploy to IPFS

on: 
  schedule:
    - cron: '0 12 * * 3,6'
  workflow_dispatch:

jobs:
  sync-code-and-deploy:
    runs-on: ubuntu-latest
    name: sync code and deploy to ipfs by crust
    env:
      CI: false

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout main
        uses: actions/checkout@v2

      - uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
        with:
          upstream_repository: OasisDEX/mcd-cdp-portal
          upstream_branch: master
          target_branch: master
          git_pull_args: --allow-unrelated-histories
          git_fetch_args: --tags
          git_push_args: --tags               
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump version and push tag
        id: bump_tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*

      - name: remove homepage
        run: yarn add edit-json-file && node edit-package.js && yarn remove edit-json-file 
          
      - name: build
        run: yarn install && yarn build

      - name: up to ipfs
        id: upload
        uses: XueMoMo/ipfs-upload-action@v1.2
        with:
          path: 'build'
          crust-secret-key: ${{ secrets.CRUST_SECRET_KEY }}
          # ipns-key: 'ipns-for-mcd-portal'

      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      # - name: update dnslink
      #   uses: decooio/cloudflare-dnslink-action@v1.0.0
      #   id: dnslink
      #   with:
      #     name: "mcd.decoo.io"
      #     cid: ${{ steps.upload.outputs.hash }}
      #     token: ${{ secrets.CLOUDFLARE_TOKEN }}
      #     zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      
      - name: order in crust
        uses: crustio/ipfs-crust-action@v1.0.8
        with:
          cid:  ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Create GitHub Release
        if: ${{ steps.upload.conclusion == 'success'}}
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          release_name: Release ${{ steps.bump_tag.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`
            - IPNS: `${{ steps.upload.outputs.ipns }}`

            You can access the Oasis Borrow Interface directly from an IPFS gateway.
            The Oasis Borrow interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store your settings.
            **Beware** that other sites you access via the _same_ IPFS gateway can read and modify your settings on the Oasis Borrow interface without your permission.
            You can avoid this issue by using a subdomain IPFS gateway.
            The preferred URLs below are safe to use to access this specific release.

            Preferred URLs:
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
